# Simple GitHub Actions Workflow for Learning
name: Hello GitHub Actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello-world"
  hello-world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a simple greeting command
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      # Display some information about the environment
      - name: Show Environment Info
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Workflow run started by: ${{ github.actor }}"

      # Show the current date and time
      - name: Show Current Date
        run: date
